const LOUNGE_DB = [
  { id: '0PBVFBRQ626H3', name: "드라마 이야기", category: "드라마" },
  { id: '0P7DE12WDXQBK', name: "오늘부터 인간입니다만", category: "드라마" },
  { id: '0P7DE12WDXQBW', name: "은애하는 도적님아", category: "드라마" },
  { id: '0P7DE12WDXQBX', name: "이 사랑 통역 되나요?", category: "드라마" },
  { id: '0P7DE12WDXQBG', name: "언더커버 미쓰홍", category: "드라마" },
  { id: '0P7DE12WDXQB4', name: "블러디 플라워", category: "드라마" },
  { id: '0P7DE12WDXQB6', name: "사랑을 처방해 드립니다", category: "드라마" },
  { id: '0P7DE12WDXQCB', name: "판사 이한영", category: "드라마" },
  { id: '0P7DE12W9XQAN', name: "레이디 두아", category: "드라마" },
  { id: '0P7DE12WDXQBF', name: "아너 : 그녀들의 법정", category: "드라마" },
  { id: '0P7DE12WDXQBQ', name: "우주를 줄게", category: "드라마" },
  { id: '0P7DE12WDXQBE', name: "아기가 생겼어요", category: "드라마" },
  { id: '0P7DE12WDXQBB', name: "스프링 피버", category: "드라마" },
  { id: '0PAJG8VKGKMP9', name: "브리저튼 시즌4", category: "드라마" },
  { id: '0P7DE12W9XQAW', name: "메이드 인 코리아", category: "드라마" },
  { id: '0P8SPK2YX4ESB', name: "친밀한 리플리", category: "드라마" },
  { id: '0P7DE12WDXQC6', name: "첫 번째 남자", category: "드라마" },
  { id: '0P7DE12WDXQC2', name: "찬란한 너의 계절에", category: "드라마" },
  { id: '0P8SP7DZN4ESA', name: "마리와 별난 아빠들", category: "드라마" },
  { id: '0P7DE12V9XQ9Z', name: "21세기 대군부인", category: "드라마" },
  { id: '0PEGVGYEF5KWE', name: "스피릿 핑거스", category: "드라마" },
  { id: '0P7DE12WDXQBZ', name: "재혼 황후", category: "드라마" },
  { id: '0P7DE12W9XQAZ', name: "미혼남녀의 효율적 만남", category: "드라마" },
  { id: '0P7DE12W9XQA1', name: "각잡힌 로맨스", category: "드라마" },
  { id: '0P7DE12W9XQAF', name: "원더풀스", category: "드라마" },
  { id: '0P7DE12W9XQAX', name: "무빙 시즌 2", category: "드라마" },
  { id: '0P7DE12WDXQB7', name: "샤이닝", category: "드라마" },
  { id: '0P7DE12W9XQA8', name: "나 혼자만 레벨업", category: "드라마" },
  { id: '0P7DE12WDXQB8', name: "세이렌", category: "드라마" },
  { id: '0PANK42BSYP8B', name: "기묘한 이야기 시즌5", category: "드라마" },
  { id: '0P7DE12W9XQAQ', name: "로또 1등도 출근합니다", category: "드라마" },
  { id: '0P7DE12WDXQC1', name: "지금 우리 학교는 시즌2", category: "드라마" },
  { id: '0P7DE12W9XQA0', name: "24분의 1", category: "드라마" },
  { id: '0P7DE12W9XQA2', name: "골드랜드", category: "드라마" },
  { id: '0P7DE12WDXQBT', name: "유미의 세포들 시즌 3", category: "드라마" },
  { id: '0P7DE12WDXQCA', name: "킬러들의 쇼핑몰 시즌2", category: "드라마" },
  { id: '0PANHM6D8KMPA', name: "더 뷰티", category: "드라마" },
  { id: '0P7DE12WDXQBR', name: "월간남친", category: "드라마" },
  { id: '0P7DE12W9XQAD', name: "대리수능", category: "드라마" },
  { id: '0P7DE12WDXQBD', name: "신이랑 법률사무소", category: "드라마" },
  { id: '0P7DE12W9XQA4', name: "귀왕", category: "드라마" },
  { id: '0P7DE12W9XQA6', name: "기리고", category: "드라마" },
  { id: '0P7DE12W9XQAB', name: "다윗의 왕국", category: "드라마" },
  { id: '0P7DE12W9XQAC', name: "닥터신", category: "드라마" },
  { id: '0P7DE12W9XQAE', name: "대한민국에서 건물주 되는 법", category: "드라마" },
  { id: '0P7DE12W9XQAT', name: "매화,달", category: "드라마" },
  { id: '0P7DE12WDXQC3', name: "참교육", category: "드라마" },
  { id: '0P7DE12WDXQC8', name: "콘크리트마켓", category: "드라마" },
  { id: '0PANJKBR38Z94', name: "교양사아", category: "드라마" },
  { id: '0P7DE12W9XQA5', name: "그랜드 갤럭시 호텔", category: "드라마" },
  { id: '0P7DE12W9XQA7', name: "꿀알바", category: "드라마" },
  { id: '0P7DE12W9XQA9', name: "나를 충전해줘", category: "드라마" },
  { id: '0P7DE12W9XQAA', name: "내가 떨릴 수 있게", category: "드라마" },
  { id: '0P7DE12W9XQAG', name: "더 웨이킹", category: "드라마" },
  { id: '0P7DE12W9XQAH', name: "동궁(가제)", category: "드라마" },
  { id: '0P7DE12W9XQAJ', name: "들쥐", category: "드라마" },
  { id: '0P7DE12W9XQAK', name: "딜러", category: "드라마" },
  { id: '0P7DE12W9XQAM', name: "러브포비아", category: "드라마" },
  { id: '0P7DE12W9XQAP', name: "로드(가제)", category: "드라마" },
  { id: '0P7DE12W9XQAR', name: "롱베이케이션", category: "드라마" },
  { id: '0P7DE12W9XQAS', name: "리버스", category: "드라마" },
  { id: '0P7DE12W9XQAV', name: "맨 끝줄 소년", category: "드라마" },
  { id: '0P7DE12W9XQAY', name: "미션 투 파서블", category: "드라마" },
  { id: '0P7DE12WDXQB0', name: "발라드", category: "드라마" },
  { id: '0P7DE12WDXQB1', name: "버라이어티", category: "드라마" },
  { id: '0P7DE12WDXQB3', name: "뷰티 인 더 비스트", category: "드라마" },
  { id: '0P7DE12WDXQB5', name: "사냥개들 시즌2", category: "드라마" },
  { id: '0P7DE12WDXQB9', name: "소년시대2", category: "드라마" },
  { id: '0P7DE12WDXQBA', name: "스캔들(가제)", category: "드라마" },
  { id: '0P7DE12WDXQBC', name: "신의 구슬", category: "드라마" },
  { id: '0P7DE12WDXQBH', name: "언프렌드", category: "드라마" },
  { id: '0P7DE12WDXQBJ', name: "오늘도 매진했습니다", category: "드라마" },
  { id: '0P7DE12WDXQBM', name: "오버캄펜세이트", category: "드라마" },
  { id: '0P7DE12WDXQBN', name: "오십프로", category: "드라마" },
  { id: '0P7DE12WDXQBP', name: "우리는 거짓말쟁이", category: "드라마" },
  { id: '0PANMMTFF8Z95', name: "원더맨", category: "드라마" },
  { id: '0P7DE12WDXQBV', name: "은밀한 감사", category: "드라마" },
  { id: '0P7DE12WDXQC0', name: "지금 불륜이 문제가 아닙니다", category: "드라마" },
  { id: '0P7DE12WDXQC4', name: "천국의 밤", category: "드라마" },
  { id: '0P7DE12WDXQC5', name: "천천히 강렬하게(가제)", category: "드라마" },
  { id: '0P7DE12WDXQC7', name: "취사병 전설이 되다", category: "드라마" },
  { id: '0P7DE12WDXQC9', name: "클라이맥스", category: "드라마" },
  { id: '0P7DE12WDXQCC', name: "폭군 시즌 2", category: "드라마" },
  { id: '0P7DE12WDXQCD', name: "할매", category: "드라마" },
  { id: '0P7DE12WDXQCE', name: "현혹", category: "드라마" },
  { id: '0PETXXZV7SM1Q', name: "붉은진주", category: "드라마" },
  { id: '0PTQ4SQY0X6M5', name: "축옥: 옥을 찾아서", category: "드라마" },
  { id: '0PTQ5PB3SVNVG', name: "기쁜 우리 좋은 날", category: "드라마" },
  { id: '0PXYZ3DQS4HP2', name: "모두가 자신의 무가치함과 싸우고 있다", category: "드라마" },
  { id: '0PYWGRNKJJGQG', name: "로맨스의 절댓값", category: "드라마" },
  { id: '0Q2RW8GF18AS2', name: "허수아비", category: "드라마" },
  { id: '0Q3B0ED6X4CVY', name: "멋진 신세계", category: "드라마" },
  { id: '0Q3R71NQYQ5HD', name: "알라르간도", category: "드라마" },
  { id: '0QB26G91J3B8T', name: "아주르스프링", category: "드라마" },
  { id: '0QB27SPB0G6CP', name: "언컨디셔널", category: "드라마" },
  { id: '0QB27XS8HBPNH', name: "러브 WiFi-궁", category: "드라마" },
  { id: '0QB2836S23B8V', name: "수상한 남편의 이중생활", category: "드라마" },
  { id: '0QGHNJ17AKG02', name: "신입사원 강회장", category: "드라마" },
  { id: '0P7DE12WSXQJQ', name: "2026 밀라노 코르티나", category: "일반 스포츠" },
  { id: '0P7DE12WSXQJR', name: "동계스포츠 이야기", category: "일반 스포츠" },
  { id: '0P7DE12WSXQJS', name: "종합격투기", category: "일반 스포츠" },
  { id: '0P7DE12WSXQJT', name: "테니스", category: "일반 스포츠" },
  { id: '0P7DE12WSXQJW', name: "워터스포츠", category: "일반 스포츠" },
  { id: '0P7DE12WSXQJX', name: "기타스포츠", category: "일반 스포츠" },
  { id: '0Q3N49G3VPBRJ', name: "F1", category: "일반 스포츠" },
  { id: '0P7DE12WXXQQC', name: "웃음뿜", category: "유머.zip" },
  { id: '0PAXT3G2B8Z96', name: "밈뿜", category: "유머.zip" },
  { id: '0P7DE12WXXQQ2', name: "사랑 고민", category: "연애" },
  { id: '0P7DE12WXXQQA', name: "MBTI/심리테스트", category: "성격/심리" },
  { id: '0PC9KW48YVKAY', name: "반려동물 이야기", category: "반려동물" },
  { id: '0P7DE12WXXQQD', name: "냥멍자랑", category: "반려동물" },
  { id: '0PCX8ACSFPAGJ', name: "자동차 이야기", category: "자동차 종합" },
  { id: '0PAZ190TYMTFA', name: "게임 이야기", category: "게임 종합" },
  { id: '0PBYCRKDD4899', name: "일상 이야기", category: "일상 수다" },
  { id: '0PBYHPKJEQMC3', name: "맛집/여행", category: "맛집/여행" },
  { id: '0PBVFQTXPQMC1', name: "예능 이야기", category: "예능" },
  { id: '0P7DE12WNXQEY', name: "현역가왕3: 프로들의 정글", category: "예능" },
  { id: '0P7DE12WHXQDE', name: "미스트롯4", category: "예능" },
  { id: '0P7DE12WHXQE9', name: "운명전쟁49", category: "예능" },
  { id: '0P7DE12WHXQDR', name: "솔로지옥 시즌5", category: "예능" },
  { id: '0P7DE12WHXQCS', name: "나는 SOLO <나는 솔로>", category: "예능" },
  { id: '0PGBBHHSNTYXB', name: "1등들", category: "예능" },
  { id: '0P7DE12WHXQCV', name: "냉장고를 부탁해 since 2014", category: "예능" },
  { id: '0P9NRW6FEFP2T', name: "Show Me The Money 12", category: "예능" },
  { id: '0PB123VVPMTFB', name: "보검 매직컬", category: "예능" },
  { id: '0P7DE12WHXQE1', name: "야구여왕", category: "예능" },
  { id: '0PBWNKSR2QMC2', name: "천하제빵 : 베이크 유어 드림", category: "예능" },
  { id: '0P7DE12WHXQCR', name: "나 혼자 산다", category: "예능" },
  { id: '0P7DE12WHXQEE', name: "이혼숙려캠프", category: "예능" },
  { id: '0P7DE12WHXQCT', name: "나는 SOLO, 그 후 사랑은 계속된다", category: "예능" },
  { id: '0P7DE12WDXQCF', name: "1박 2일 시즌4", category: "예능" },
  { id: '0PANHXB9FP5YT', name: "미스터리 수사단 시즌2", category: "예능" },
  { id: '0PKNTPPQWQK5N', name: "무명전설", category: "예능" },
  { id: '0P7DE12WHXQCM', name: "구해줘! 홈즈", category: "예능" },
  { id: '0P7DE12WHXQCN', name: "극한84", category: "예능" },
  { id: '0P7DE12WHXQDT', name: "쇼미더머니12: 야차의 세계", category: "예능" },
  { id: '0P7DE12WHXQEM', name: "조선의 사랑꾼", category: "예능" },
  { id: '0PBK2J8FQ1ND8', name: "마니또 클럽", category: "예능" },
  { id: '0P7DE12WHXQCX', name: "놀면 뭐하니?", category: "예능" },
  { id: '0PHABREE80F3Y', name: "풍향고2", category: "예능" },
  { id: '0P7DE12WNXQEX', name: "헬스파머", category: "예능" },
  { id: '0P7DE12WHXQDG', name: "미친맛집: 미식가 친구의 맛집", category: "예능" },
  { id: '0P7DE12WHXQDK', name: "불후의 명곡", category: "예능" },
  { id: '0P7DE12WHXQD5', name: "런닝맨", category: "예능" },
  { id: '0PANN1G4QP5YW', name: "금타는 금요일", category: "예능" },
  { id: '0PAVZTB5VP5YX', name: "셰프와 사냥꾼", category: "예능" },
  { id: '0P7DE12WHXQDA', name: "뮤직뱅크", category: "예능" },
  { id: '0P7DE12WHXQCY', name: "대학전쟁", category: "예능" },
  { id: '0P7DE12WHXQEA', name: "유 퀴즈 온 더 블럭", category: "예능" },
  { id: '0PKWJQJKRQK5P', name: "내 새끼의 연애2", category: "예능" },
  { id: '0PKWKXZRCJ02A', name: "방과후 태리쌤", category: "예능" },
  { id: '0P7DE12WHXQCJ', name: "골 때리는 그녀들", category: "예능" },
  { id: '0P7DE12WHXQEF', name: "SBS 인기가요", category: "예능" },
  { id: '0PAPPBD04JQ0X', name: "환승연애4", category: "예능" },
  { id: '0P7DE12WHXQDS', name: "쇼! 음악중심", category: "예능" },
  { id: '0P7DE12WHXQDX', name: "싱어게인4", category: "예능" },
  { id: '0P8SQ3EH6BGJ0', name: "아빠하고 나하고", category: "예능" },
  { id: '0P7DE12WHXQCP', name: "요즘 육아 금쪽같은 내 새끼", category: "예능" },
  { id: '0P7DE12WHXQD0', name: "더 시즌즈", category: "예능" },
  { id: '0PFRHJ8TXTYXA', name: "자매치킨", category: "예능" },
  { id: '0P7DE12WHXQCK', name: "공양간의 셰프들", category: "예능" },
  { id: '0PANJPR8VP5YV', name: "남의연애 시즌4", category: "예능" },
  { id: '0PANK8AB8JQ0W', name: "흑백요리사: 요리 계급 전쟁 시즌2", category: "예능" },
  { id: '0P7DE12WHXQE0', name: "야구기인 임찬규", category: "예능" },
  { id: '0P7DE12WHXQD8', name: "모태솔로지만 연애는 하고 싶어", category: "예능" },
  { id: '0PAYZ7GJ6MTF9', name: "내겐 너무 까칠한 매니저 - 비서진", category: "예능" },
  { id: '0P7DE12WHXQEH', name: "전지적 참견 시점", category: "예능" },
  { id: '0P7DE12WHXQEC', name: "이서진의 달라달라", category: "예능" },
  { id: '0PANM4YNSYP8D', name: "ON THE MAP (온더맵)", category: "예능" },
  { id: '0P7DE12WDXQCG', name: "개그콘서트", category: "예능" },
  { id: '0P7DE12WDXQCH', name: "개는 훌륭하다", category: "예능" },
  { id: '0P8SQ6JG6E002', name: "자식방생프로젝트 합숙 맞선", category: "예능" },
  { id: '0P7DE12WHXQCZ', name: "대환장 기안장", category: "예능" },
  { id: '0P7DE12WHXQDY', name: "아는 형님", category: "예능" },
  { id: '0P7DE12WHXQDM', name: "사장님 귀는 당나귀 귀", category: "예능" },
  { id: '0P7DE12WNXQEQ', name: "출발! 비디오 여행", category: "예능" },
  { id: '0P7DE12WHXQCW', name: "놀라운 토요일", category: "예능" },
  { id: '0P7DE12WHXQDP', name: "셀럽병사의 비밀", category: "예능" },
  { id: '0P7DE12WHXQDD', name: "복면가왕", category: "예능" },
  { id: '0P7DE12WNXQER', name: "톡파원 25시", category: "예능" },
  { id: '0P7DE12WHXQD1', name: "데블스 플랜", category: "예능" },
  { id: '0P7DE12WHXQD2', name: "도라이버", category: "예능" },
  { id: '0P7DE12WHXQD4', name: "라디오스타", category: "예능" },
  { id: '0P7DE12WHXQD6', name: "마스크 셰프", category: "예능" },
  { id: '0P7DE12WHXQE4', name: "영화가 좋다", category: "예능" },
  { id: '0P7DE12WHXQE5', name: "옥탑방의 문제아들", category: "예능" },
  { id: '0P7DE12WNXQEP', name: "최강야구", category: "예능" },
  { id: '0P7DE12WHXQE3', name: "열혈농구단", category: "예능" },
  { id: '0P7DE12WHXQD7', name: "말자쇼", category: "예능" },
  { id: '0P7DE12WHXQDH', name: "벌거벗은 세계사", category: "예능" },
  { id: '0P7DE12WHXQDN', name: "살림하는 남자들", category: "예능" },
  { id: '0P7DE12WHXQDV', name: "슈퍼맨이 돌아왔다", category: "예능" },
  { id: '0P7DE12WHXQDW', name: "신상출시 편스토랑", category: "예능" },
  { id: '0P7DE12WNXQEN', name: "직장인들", category: "예능" },
  { id: '0P7DE12WNXQET', name: "틈만 나면,", category: "예능" },
  { id: '0P7DE12WNXQEZ', name: "스튜디오 K", category: "예능" },
  { id: '0P7DE12WHXQCQ', name: "끝까지 간다", category: "예능" },
  { id: '0P7DE12WHXQD3', name: "동상이몽 2 - 너는 내 운명", category: "예능" },
  { id: '0P7DE12WHXQD9', name: "뭉쳐야 찬다 4", category: "예능" },
  { id: '0P7DE12WHXQDF', name: "미운 우리 새끼", category: "예능" },
  { id: '0P7DE12WHXQDJ', name: "범죄자의 편지를 읽다", category: "예능" },
  { id: '0P7DE12WHXQDQ', name: "속풀이쇼 동치미", category: "예능" },
  { id: '0P7DE12WHXQE2', name: "엄지의 제왕", category: "예능" },
  { id: '0P7DE12WHXQE6', name: "옷장전쟁", category: "예능" },
  { id: '0P7DE12WHXQE7', name: "요즘 남자 라이프 - 신랑수업", category: "예능" },
  { id: '0P7DE12WHXQE8', name: "알토란", category: "예능" },
  { id: '0P7DE12WHXQEB', name: "유재석 캠프", category: "예능" },
  { id: '0P7DE12WHXQED', name: "이제 만나러 갑니다", category: "예능" },
  { id: '0P7DE12WHXQEG', name: "장도바리바리", category: "예능" },
  { id: '0P7DE12WHXQEJ', name: "전현무계획", category: "예능" },
  { id: '0P7DE12WHXQEK', name: "접속! 무비월드", category: "예능" },
  { id: '0P7DE12WNXQEV', name: "퍼펙트 글로우", category: "예능" },
  { id: '0P7DE12WNXQEW', name: "푹 쉬면 다행이야", category: "예능" },
  { id: '0PTNS52HGX1JH', name: "BTS 컴백 라이브: ARIRANG", category: "예능" },
  { id: '0PTQ54X6WX6M6', name: "신랑수업2", category: "예능" },
  { id: '0PTQ5FJ0MX1JJ', name: "심우면 연리리", category: "예능" },
  { id: '0PWAHCS87P5VY', name: "강호동네서점", category: "예능" },
  { id: '0PYWGXWRS4HP3', name: "하트시그널5", category: "예능" },
  { id: '0PYWH9MD5ENNN', name: "구기동 프렌즈", category: "예능" },
  { id: '0PYWHBAH54HP4', name: "언니네 산지직송 in 칼라페", category: "예능" },
  { id: '0PYWHDNE2JGQH', name: "2026 한일가왕전", category: "예능" },
  { id: '0PYWHG66AJGQJ', name: "우리동네 야구대장", category: "예능" },
  { id: '0Q2P89G4VP5W2', name: "상남자의 여행법 in 규슈", category: "예능" },
  { id: '0Q2PE5JEJJGQN', name: "돌싱N모솔", category: "예능" },
  { id: '0Q2PENRTNENNQ', name: "앙상블", category: "예능" },
  { id: '0Q2PHEHCVP5W3', name: "X의 사생활", category: "예능" },
  { id: '0Q3MYWCPNN4N6', name: "할루시네이션 : 해고 전쟁", category: "예능" },
  { id: '0Q3R7BAFS4CVZ', name: "최강로드 식포일러", category: "예능" },
  { id: '0Q4A1TQYSV40C', name: "소라와 진경", category: "예능" },
  { id: '0Q4A24JWSV40D', name: "우리 듀엣할까요", category: "예능" },
  { id: '0Q58XE7GXV40E', name: "태군노래자랑4", category: "예능" },
  { id: '0Q58YWXGN4CW1', name: "인기가요 ON THE GO", category: "예능" },
  { id: '0Q58Z5BNZPBRX', name: "주방참견 셰프들의 오픈런", category: "예능" },
  { id: '0Q5WXVMDVPBS2', name: "꽃보다 청춘 : 리미티드 에디션", category: "예능" },
  { id: '0Q5WY444YQ5HE', name: "최우수산", category: "예능" },
  { id: '0Q5WYEM8DV40F', name: "킬잇 : 스타일 크리에이터 대전쟁", category: "예능" },
  { id: '0Q5WYR24DV40G', name: "더 스카웃", category: "예능" },
  { id: '0Q79Q21YCG6CD', name: "요리는 괴로워!", category: "예능" },
  { id: '0Q7AJE7P3TXFR', name: "봉주르빵집", category: "예능" },
  { id: '0Q8VK2THQ20P6', name: "디렉터스 아레나", category: "예능" },
  { id: '0Q8VMAG1E49K4', name: "생존왕 2", category: "예능" },
  { id: '0Q8VN3337TXFT', name: "언더커버 셰프", category: "예능" },
  { id: '0Q8W1Z2NMG6CH', name: "미스트롯 포유", category: "예능" },
  { id: '0Q9T0H49NBPNA', name: "히든싱어8", category: "예능" },
  { id: '0Q9TAJKJGG6CJ', name: "시골마을 이장우3", category: "예능" },
  { id: '0QADGAXCY49K7', name: "누난 내게 여자야 시즌2", category: "예능" },
  { id: '0QADGKDJ5BPND', name: "해피투게더 - 혼자가 아니어서 좋아", category: "예능" },
  { id: '0QADGVRBY49K8', name: "스트릿 월드 파이터 : 디렉터스 워", category: "예능" },
  { id: '0QADH3VHHBPNE', name: "메추리 원정대", category: "예능" },
  { id: '0QADHC3C7TXFZ', name: "남의 집 귀한 가족", category: "예능" },
  { id: '0QADHMJBDBPNF', name: "쯔양몇끼", category: "예능" },
  { id: '0QCNEGGWP9FBT', name: "법륜로드 : 스님과 손님", category: "예능" },
  { id: '0QE90RG97JT2B', name: "한국탐구여행", category: "예능" },
  { id: '0QE910PY0JXKP', name: "누난 내게 여자야 2", category: "예능" },
  { id: '0QE918W8A5PW2', name: "닥치고 한일전", category: "예능" },
  { id: '0QE91H0QZJT2C', name: "스트릿 레스토랑 파이터", category: "예능" },
  { id: '0QGV38V8J5PWB', name: "위대한 가이드3", category: "예능" },
  { id: '0QGV3DH5FJT2E', name: "은밀한 여자들 : 적과의 동거", category: "예능" },
  { id: '0QGV4JKVSBSQX', name: "오페라캠퍼스", category: "예능" },
  { id: '0QGV4Q79P5PWC', name: "연애전쟁", category: "예능" },
  { id: '0QGV4VTTT9FC0', name: "웰컴 투 수근스쿨", category: "예능" },
  { id: '0P7DE12WNXQHP', name: "야구 이야기", category: "야구" },
  { id: '0P7DE12WNXQHQ', name: "삼성 라이온즈", category: "야구" },
  { id: '0P7DE12WNXQHX', name: "한화 이글스", category: "야구" },
  { id: '0P7DE12WNXQHR', name: "LG 트윈스", category: "야구" },
  { id: '0P7DE12WNXQHY', name: "롯데 자이언츠", category: "야구" },
  { id: '0P7DE12WNXQHV', name: "KIA 타이거즈", category: "야구" },
  { id: '0P7DE12WNXQHS', name: "두산 베어스", category: "야구" },
  { id: '0P7DE12WNXQHT', name: "SSG 랜더스", category: "야구" },
  { id: '0P7DE12WNXQHW', name: "NC 다이노스", category: "야구" },
  { id: '0P7DE12WNXQHZ', name: "키움 히어로즈", category: "야구" },
  { id: '0P7DE12WNXQJ0', name: "KT 위즈", category: "야구" },
  { id: '0P7DE12WXXQQ3', name: "결혼생활 고민", category: "결혼/가족" },
  { id: '0P7DE12WXXQQ4', name: "가족문제", category: "결혼/가족" },
  { id: '0P7DE12WXXQQB', name: "사주/타로/운세", category: "운세/점술" },
  { id: '0P7DE12WSXQMD', name: "액티언", category: "KGM" },
  { id: '0P7DE12WSXQME', name: "렉스턴", category: "KGM" },
  { id: '0P7DE12WSXQMF', name: "코란도", category: "KGM" },
  { id: '0P7DE12WSXQMG', name: "티볼리", category: "KGM" },
  { id: '0P7DE12WSXQMH', name: "토레스", category: "KGM" },
  { id: '0P7DE12WSXQP5', name: "LOL", category: "PC 게임" },
  { id: '0P7DE12WSXQP2', name: "오버워치", category: "PC 게임" },
  { id: '0PBYN236D489B', name: "문화/취미", category: "문화/취미" },
  { id: '0PC9QAE9J26H5', name: "애니 이야기", category: "애니메이션" },
  { id: '0P7DE12WNXQFA', name: "SF 애니", category: "애니메이션" },
  { id: '0P7DE12WNXQF0', name: "가족 애니", category: "애니메이션" },
  { id: '0P7DE12WNXQF1', name: "단편 애니", category: "애니메이션" },
  { id: '0P7DE12WNXQF2', name: "러브코미디 애니", category: "애니메이션" },
  { id: '0P7DE12WNXQF3', name: "모험 애니", category: "애니메이션" },
  { id: '0P7DE12WNXQF4', name: "밴드 애니", category: "애니메이션" },
  { id: '0P7DE12WNXQF5', name: "순정/로맨스 애니", category: "애니메이션" },
  { id: '0P7DE12WNXQF6', name: "아이돌 애니", category: "애니메이션" },
  { id: '0P7DE12WNXQF7', name: "액션 애니", category: "애니메이션" },
  { id: '0P7DE12WNXQF8', name: "판타지 애니", category: "애니메이션" },
  { id: '0P7DE12WNXQF9', name: "학원 애니", category: "애니메이션" },
  { id: '0P7DE12WNXQJ2', name: "축구 이야기", category: "축구" },
  { id: '0P7DE12WNXQJ3', name: "K리그1", category: "축구" },
  { id: '0P7DE12WNXQJ4', name: "K리그2", category: "축구" },
  { id: '0P7DE12WSXQJC', name: "대한민국 대표팀", category: "축구" },
  { id: '0P7DE12WXXQQ9', name: "직장생활 고민", category: "직장생활" },
  { id: '0P7DE12WSXQKJ', name: "카니발", category: "기아자동차" },
  { id: '0P7DE12WSXQKK', name: "모닝", category: "기아자동차" },
  { id: '0P7DE12WSXQKM', name: "쏘렌토", category: "기아자동차" },
  { id: '0P7DE12WSXQKN', name: "스포티지", category: "기아자동차" },
  { id: '0P7DE12WSXQKP', name: "K5", category: "기아자동차" },
  { id: '0P7DE12WSXQKQ', name: "K9", category: "기아자동차" },
  { id: '0P7DE12WSXQKR', name: "레이", category: "기아자동차" },
  { id: '0P7DE12WSXQKS', name: "봉고", category: "기아자동차" },
  { id: '0P7DE12WSXQKT', name: "셀토스", category: "기아자동차" },
  { id: '0P7DE12WSXQKV', name: "K8", category: "기아자동차" },
  { id: '0P7DE12WSXQKW', name: "EV6", category: "기아자동차" },
  { id: '0P7DE12WSXQKX', name: "EV9", category: "기아자동차" },
  { id: '0P7DE12WSXQKY', name: "EV5", category: "기아자동차" },
  { id: '0P7DE12WSXQKZ', name: "EV3", category: "기아자동차" },
  { id: '0P7DE12WSXQM0', name: "EV4", category: "기아자동차" },
  { id: '0P7DE12WSXQM1', name: "타스만", category: "기아자동차" },
  { id: '0P7DE12WSXQM2', name: "PV5", category: "기아자동차" },
  { id: '0P7DE12WXXQPR', name: "피크민블룸", category: "모바일 게임" },
  { id: '0P7DE12WXXQPC', name: "명일방주 : 엔드필드", category: "모바일 게임" },
  { id: '0P7DE12WXXQPD', name: "명조 : 워더링웨이브", category: "모바일 게임" },
  { id: '0PBVFKCFZ1ND9', name: "영화 이야기", category: "영화" },
  { id: '0P7DE12WNXQGZ', name: "왕과 사는 남자", category: "영화" },
  { id: '0P7DE12WNXQHM', name: "휴민트", category: "영화" },
  { id: '0PHAC5KQDTYXC', name: "파반느", category: "영화" },
  { id: '0PCH1YYD226H6', name: "노 머시: 90분", category: "영화" },
  { id: '0P7DE12WNXQGT', name: "악마는 프라다를 입는다 2", category: "영화" },
  { id: '0P8SRMPZEE003', name: "만약에 우리", category: "영화" },
  { id: '0P7DE12WNXQHE', name: "프로젝트 Y", category: "영화" },
  { id: '0PBTN7112VKAV', name: "케이팝 데몬 헌터스", category: "영화" },
  { id: '0P8SRVB86BGJ1', name: "주토피아 2", category: "영화" },
  { id: '0P7DE12WNXQGP', name: "시라트", category: "영화" },
  { id: '0P8SRSDZAE005', name: "아바타: 불과 재", category: "영화" },
  { id: '0P7DE12WNXQH3', name: "직장상사 길들이기", category: "영화" },
  { id: '0P7DE12WNXQFD', name: "28년 후: 뼈의 사원", category: "영화" },
  { id: '0P8SRPR2EE004', name: "신의악단", category: "영화" },
  { id: '0P7DE12WNXQH8', name: "토이 스토리 5", category: "영화" },
  { id: '0P7DE12WNXQFB', name: "731", category: "영화" },
  { id: '0P7DE12WNXQGW', name: "어벤져스: 둠스데이", category: "영화" },
  { id: '0P8SRXEH6BGJ2', name: "천공의 성 라퓨타", category: "영화" },
  { id: '0P7DE12WNXQFS', name: "끝이 없는 스칼렛", category: "영화" },
  { id: '0P7DE12WNXQFJ', name: "광장", category: "영화" },
  { id: '0P7DE12WNXQG0', name: "대홍수", category: "영화" },
  { id: '0P7DE12WNXQGJ', name: "슈퍼 마리오 갤럭시", category: "영화" },
  { id: '0P7DE12WNXQHH', name: "하트맨", category: "영화" },
  { id: '0P7DE12WNXQH4', name: "초속 5센티미터", category: "영화" },
  { id: '0P7DE12WNXQFC', name: "1026: 새로운 세상을 위한", category: "영화" },
  { id: '0P7DE12WNXQFH', name: "고고다이노 극장판: 곤충세계 대모험", category: "영화" },
  { id: '0P7DE12WNXQFN', name: "굿 포츈", category: "영화" },
  { id: '0P7DE12WNXQFQ', name: "극장판 엉덩이 탐정: 스타 앤드 문", category: "영화" },
  { id: '0P7DE12WNXQG6', name: "리틀 아멜리", category: "영화" },
  { id: '0P7DE12WNXQG8', name: "마이클", category: "영화" },
  { id: '0P7DE12WNXQG9', name: "모아나", category: "영화" },
  { id: '0P7DE12WNXQH9', name: "톰과 제리: 황금나침반 대소동", category: "영화" },
  { id: '0P7DE12WNXQHG', name: "하우스메이드", category: "영화" },
  { id: '0P7DE12WNXQFX', name: "내 곁에 온 걸 환영해", category: "영화" },
  { id: '0P7DE12WNXQG5', name: "러브 인 베트남", category: "영화" },
  { id: '0P7DE12WNXQGK', name: "슈퍼걸", category: "영화" },
  { id: '0P7DE12WNXQGM', name: "스노우 폭스 : 마법의 돌을 찾아서", category: "영화" },
  { id: '0P7DE12WNXQGN', name: "스폰지밥 무비: 네모바지를 찾아서", category: "영화" },
  { id: '0P7DE12WNXQGQ', name: "시수: 복수의 길", category: "영화" },
  { id: '0P7DE12WNXQGR', name: "시스터", category: "영화" },
  { id: '0P7DE12WNXQGS', name: "신비아파트 10주년 극장판: 한 번 더, 소환", category: "영화" },
  { id: '0P7DE12WNXQGV', name: "어리석은 자는 누구인가", category: "영화" },
  { id: '0P7DE12WNXQGX', name: "얼음 여왕", category: "영화" },
  { id: '0P7DE12WNXQGY', name: "오디세이", category: "영화" },
  { id: '0P7DE12WNXQH2', name: "정글비트 2", category: "영화" },
  { id: '0P7DE12WNXQH5', name: "초혼, 우리들의 노래", category: "영화" },
  { id: '0P7DE12WNXQH6', name: "크로스 2", category: "영화" },
  { id: '0P7DE12WNXQH7', name: "타이고", category: "영화" },
  { id: '0P7DE12WNXQHA', name: "튜즈데이", category: "영화" },
  { id: '0P7DE12WNXQHB', name: "판결", category: "영화" },
  { id: '0P7DE12WNXQHC', name: "폭풍의 언덕", category: "영화" },
  { id: '0P7DE12WNXQHD', name: "프라이메이트", category: "영화" },
  { id: '0P7DE12WNXQHF', name: "피렌체", category: "영화" },
  { id: '0P7DE12WNXQHJ', name: "햄넷", category: "영화" },
  { id: '0P7DE12WNXQHK', name: "호퍼스", category: "영화" },
  { id: '0P7DE12WNXQFE', name: "가능한 사랑", category: "영화" },
  { id: '0P7DE12WNXQFF', name: "가시나무새", category: "영화" },
  { id: '0P7DE12WNXQFK', name: "군체", category: "영화" },
  { id: '0P7DE12WNXQFM', name: "굿 포 낫씽", category: "영화" },
  { id: '0P7DE12WNXQFP', name: "극장판 뿌이뿌이 모루카 MOLMAX (모루맥스)", category: "영화" },
  { id: '0P7DE12WNXQFR', name: "김~치!", category: "영화" },
  { id: '0P7DE12WNXQFT', name: "나는 갱년기다", category: "영화" },
  { id: '0P7DE12WNXQFV', name: "나만의 비밀", category: "영화" },
  { id: '0P7DE12WNXQFW', name: "남편들", category: "영화" },
  { id: '0P7DE12WNXQFY', name: "넘버원", category: "영화" },
  { id: '0P7DE12WNXQG1', name: "동창 : 최후의 만찬", category: "영화" },
  { id: '0P7DE12WNXQG2', name: "두 번째 계절", category: "영화" },
  { id: '0P7DE12WNXQG3', name: "드림 홈", category: "영화" },
  { id: '0P7DE12WNXQG4', name: "디스클로저 데이", category: "영화" },
  { id: '0P7DE12WNXQG7', name: "마이 선샤인", category: "영화" },
  { id: '0P7DE12WNXQGA', name: "물의 연대기", category: "영화" },
  { id: '0P7DE12WNXQGB', name: "부흥", category: "영화" },
  { id: '0P7DE12WNXQGC', name: "브라이드!", category: "영화" },
  { id: '0P7DE12WNXQGE', name: "송 썽 블루", category: "영화" },
  { id: '0P7DE12WNXQGF', name: "수궁", category: "영화" },
  { id: '0P7DE12WNXQGG', name: "쉬 캠 투 미", category: "영화" },
  { id: '0P7DE12WNXQGH', name: "슈가", category: "영화" },
  { id: '0PVMDMNFDPR0D', name: "프로젝트 헤일메리", category: "영화" },
  { id: '0Q214SFS62P5A', name: "살목지", category: "영화" },
  { id: '0Q2PF0SSX4HP8', name: "내 이름은", category: "영화" },
  { id: '0Q2PX8WE22P5C', name: "쉘터", category: "영화" },
  { id: '0Q2RWZJG54HPA', name: "호프", category: "영화" },
  { id: '0Q2RZ9A162P5E', name: "침묵의 친구", category: "영화" },
  { id: '0Q2S5F0HD8AS4', name: "고트: 더 레전드", category: "영화" },
  { id: '0Q323KBJ9ENNS', name: "노멀", category: "영화" },
  { id: '0Q323MPTX4HPB', name: "붉은 10월의 반란 파트 2", category: "영화" },
  { id: '0Q323P2CAJGQQ', name: "짱구", category: "영화" },
  { id: '0Q323QDX94HPC', name: "리 크로닌의 미이라", category: "영화" },
  { id: '0Q323RSM7P5W5', name: "르누아르", category: "영화" },
  { id: '0Q58XV91ZPBRW', name: "미스매치", category: "영화" },
  { id: '0Q58Y58AHN4N8', name: "줄무늬 파자마를 입은 소년", category: "영화" },
  { id: '0Q58YETC54CW0', name: "오시리스", category: "영화" },
  { id: '0Q8VQF328G6CF', name: "캣 앤 독", category: "영화" },
  { id: '0Q8VRCB7RG6CG', name: "모탈 컴뱃 2", category: "영화" },
  { id: '0Q8VRVEGA49K5', name: "그녀가 돌아온 날", category: "영화" },
  { id: '0Q8VSAZFNBPN9', name: "올 그린스", category: "영화" },
  { id: '0QA55BN5CG6CK', name: "로빈슨 크루소", category: "영화" },
  { id: '0QADCS8KY49K6', name: "교생실습", category: "영화" },
  { id: '0QADCXF87TXFW', name: "피어스", category: "영화" },
  { id: '0QADD1E03TXFX', name: "파티마가 사랑한 계절", category: "영화" },
  { id: '0QADD5N1HBPNC', name: "훈련사", category: "영화" },
  { id: '0QADD9VSVTXFY', name: "5월18일생", category: "영화" },
  { id: '0QADDE35J3B8P', name: "꽃잎", category: "영화" },
  { id: '0QADDR37720P8', name: "한복 입은 남자", category: "영화" },
  { id: '0QADDWABQ20P9', name: "아이엠 포포", category: "영화" },
  { id: '0QADEHT0J3B8Q', name: "너바나 더 밴드", category: "영화" },
  { id: '0QAF2VF5CG6CN', name: "데몬 샤크 헌터스", category: "영화" },
  { id: '0QAF3403HBPNG', name: "복수의 립스틱", category: "영화" },
  { id: '0QAFP2NYVTXG1', name: "와일드 씽", category: "영화" },
  { id: '0QBS69C31BPNJ', name: "탑건: 매버릭", category: "영화" },
  { id: '0QBS6M8XNBPNK', name: "뱅: 킬러 리턴즈", category: "영화" },
  { id: '0QE8YQ2B5BSQR', name: "이상한 과자 가게 전천당", category: "영화" },
  { id: '0QE8YZ7J9BSQS', name: "백룸", category: "영화" },
  { id: '0QE8Z7C9E9FBV', name: "파이널 피스", category: "영화" },
  { id: '0QE8ZFJAAKFZV', name: "엔조", category: "영화" },
  { id: '0QE8ZQQZT9FBW', name: "만달로리안과 그로구", category: "영화" },
  { id: '0QE8ZZXXZJT2A', name: "유레카", category: "영화" },
  { id: '0QE9084H1BSQT', name: "쇼타씨의 마지막 출장", category: "영화" },
  { id: '0QE90G9V0JXKN', name: "뒷자리에 태워줘", category: "영화" },
  { id: '0QGV1ES2J5PW9', name: "몽그렐스", category: "영화" },
  { id: '0QGV1KEC4JXKQ', name: "리마인더스 오브 힘", category: "영화" },
  { id: '0QGV2B52CJXKR', name: "이인", category: "영화" },
  { id: '0QGV2FSD6KG03', name: "더 파이터: 리벤지", category: "영화" },
  { id: '0QGV2MDYJKG04', name: "검객 생과사", category: "영화" },
  { id: '0QGV2S31TKG05', name: "킬러웨일: 침묵의 습격자", category: "영화" },
  { id: '0QGV3J4XZJT2F', name: "스페이스 타임", category: "영화" },
  { id: '0QGV3PSPP9FBZ', name: "밀월", category: "영화" },
  { id: '0QGV3VD5CJXKS', name: "마스터즈 오브 유니버스", category: "영화" },
  { id: '0QGV4013FJT2G', name: "상자 속의 양", category: "영화" },
  { id: '0QGV44P5GJXKT', name: "이반리 장만옥", category: "영화" },
  { id: '0QGV49AFQJT2H', name: "현상수배", category: "영화" },
  { id: '0QGV4DZ3JKG06', name: "위대한 환상", category: "영화" },
  { id: '0QGV7C2X65PWG', name: "로메리아", category: "영화" },
  { id: '0QGVGDDFPKG0A', name: "닥터 섬보이", category: "영화" },
  { id: '0QGVGJHDTKG0B', name: "내일도 출근!", category: "영화" },
  { id: '0QGVGQPHJKG0C', name: "김부장", category: "영화" },
  { id: '0QGVGWV1MJXKW', name: "결혼의 완성", category: "영화" },
  { id: '0QGVH1ZMJ9FC5', name: "가족관계증명서", category: "영화" },
  { id: '0QGVH73CCJXKX', name: "오싹한 연애", category: "영화" },
  { id: '0P7DE12WSXQJY', name: "걷기/런닝", category: "아웃도어" },
  { id: '0P7DE12WSXQJZ', name: "등산/캠핑", category: "아웃도어" },
  { id: '0P7DE12WSXQK0', name: "자전거/바이크", category: "아웃도어" },
  { id: '0P7DE12WSXQK1', name: "피트니스", category: "아웃도어" },
  { id: '0P7DE12WXXQQ5', name: "초등학생 고민방", category: "학교생활" },
  { id: '0P7DE12WXXQQ6', name: "중학생 고민방", category: "학교생활" },
  { id: '0P7DE12WXXQQ7', name: "고등학생 고민방", category: "학교생활" },
  { id: '0P7DE12WXXQQ8', name: "대학생 고민방", category: "학교생활" },
  { id: '0P7DE12WSXQMZ', name: "테슬라", category: "기타 자동차 브랜드" },
  { id: '0P7DE12WSXQMS', name: "포르쉐", category: "기타 자동차 브랜드" },
  { id: '0P7DE12WSXQMR', name: "BMW", category: "기타 자동차 브랜드" },
  { id: '0P7DE12WSXQMN', name: "아우디", category: "기타 자동차 브랜드" },
  { id: '0P7DE12WSXQNF', name: "BYD", category: "기타 자동차 브랜드" },
  { id: '0P7DE12WSXQMQ', name: "메르세데스-벤츠", category: "기타 자동차 브랜드" },
  { id: '0P7DE12WSXQMX', name: "지프", category: "기타 자동차 브랜드" },
  { id: '0P7DE12WSXQN7', name: "미니", category: "기타 자동차 브랜드" },
  { id: '0P7DE12WSXQMT', name: "캐딜락", category: "기타 자동차 브랜드" },
  { id: '0P7DE12WSXQMY', name: "GMC", category: "기타 자동차 브랜드" },
  { id: '0P7DE12WSXQN0', name: "볼보", category: "기타 자동차 브랜드" },
  { id: '0P7DE12WSXQN1', name: "폴스타", category: "기타 자동차 브랜드" },
  { id: '0P7DE12WSXQN2', name: "랜드로버", category: "기타 자동차 브랜드" },
  { id: '0P7DE12WSXQN8', name: "맥라렌", category: "기타 자동차 브랜드" },
  { id: '0P7DE12WSXQNA', name: "람보르기니", category: "기타 자동차 브랜드" },
  { id: '0P7DE12WSXQNB', name: "마세라티", category: "기타 자동차 브랜드" },
  { id: '0P7DE12WSXQNE', name: "토요타", category: "기타 자동차 브랜드" },
  { id: '0P7DE12WSXQNJ', name: "대창모터스", category: "기타 자동차 브랜드" },
  { id: '0P7DE12WSXQMP', name: "폭스바겐", category: "기타 자동차 브랜드" },
  { id: '0P7DE12WSXQMV', name: "포드", category: "기타 자동차 브랜드" },
  { id: '0P7DE12WSXQMW', name: "링컨", category: "기타 자동차 브랜드" },
  { id: '0P7DE12WSXQN3', name: "롤스로이스", category: "기타 자동차 브랜드" },
  { id: '0P7DE12WSXQN4', name: "애스턴마틴", category: "기타 자동차 브랜드" },
  { id: '0P7DE12WSXQN5', name: "로터스", category: "기타 자동차 브랜드" },
  { id: '0P7DE12WSXQN6', name: "벤틀리", category: "기타 자동차 브랜드" },
  { id: '0P7DE12WSXQN9', name: "페라리", category: "기타 자동차 브랜드" },
  { id: '0P7DE12WSXQNC', name: "렉서스", category: "기타 자동차 브랜드" },
  { id: '0P7DE12WSXQND', name: "혼다", category: "기타 자동차 브랜드" },
  { id: '0P7DE12WSXQNG', name: "동풍소콘", category: "기타 자동차 브랜드" },
  { id: '0P7DE12WSXQNH', name: "푸조", category: "기타 자동차 브랜드" },
  { id: '0P7DE12WSXQNK', name: "모빌리티네트웍스", category: "기타 자동차 브랜드" },
  { id: '0P7DE12WSXQNM', name: "제이스모빌리티", category: "기타 자동차 브랜드" },
  { id: '0P7DE12WSXQNN', name: "캠시스", category: "기타 자동차 브랜드" },
  { id: '0P7DE12WSXQNP', name: "마이브", category: "기타 자동차 브랜드" },
  { id: '0P7DE12WXXQPT', name: "닌텐도", category: "콘솔/플랫폼 게임" },
  { id: '0P7DE12WXXQPV', name: "스팀", category: "콘솔/플랫폼 게임" },
  { id: '0P7DE12WXXQPW', name: "플레이스테이션", category: "콘솔/플랫폼 게임" },
  { id: '0PBYQXD6TVKAX', name: "내돈내산", category: "내돈내산" },
  { id: '0Q2FJ9X9D4HP5', name: "제62회 백상예술대상 with 구찌", category: "연예•영화 시상식" },
  { id: '0Q2RX9319ENNR', name: "79회 칸영화제", category: "연예•영화 시상식" },
  { id: '0Q87Q8SJ3TXFS', name: "27회 전주국제영화제", category: "연예•영화 시상식" },
  { id: '0QDQNW5VPKFZT', name: "22회 미쟝센단편영화제", category: "연예•영화 시상식" },
  { id: '0P7DE12WSXQJF', name: "농구 이야기", category: "농구" },
  { id: '0P7DE12WSXQJG', name: "NBA", category: "농구" },
  { id: '0P7DE12WSXQJH', name: "KBL", category: "농구" },
  { id: '0P7DE12WSXQJJ', name: "WKBL", category: "농구" },
  { id: '0P7DE12WSXQM9', name: "SM6", category: "르노코리아" },
  { id: '0P7DE12WSXQMA', name: "QM6", category: "르노코리아" },
  { id: '0P7DE12WSXQMB', name: "아르카나", category: "르노코리아" },
  { id: '0P7DE12WSXQMC', name: "그랑 콜레오스", category: "르노코리아" },
  { id: '0PNV6ZFJW1H1G', name: "필랑트", category: "르노코리아" },
  { id: '0Q2PVAZM54HP9', name: "코첼라 2026", category: "공연•페스티벌" },
  { id: '0QH973QBZJT2M', name: "월드 디제이 페스티벌", category: "공연•페스티벌" },
  { id: '0QH97NXVA9FC6', name: "워터밤 서울 2026", category: "공연•페스티벌" },
  { id: '0P7DE12WSXQJK', name: "배구 이야기", category: "배구" },
  { id: '0P7DE12WSXQJM', name: "V-리그 여자부", category: "배구" },
  { id: '0P7DE12WSXQJN', name: "V-리그 남자부", category: "배구" },
  { id: '0P7DE12WSXQMJ', name: "트랙스", category: "쉐보레" },
  { id: '0P7DE12WSXQMK', name: "콜로라도", category: "쉐보레" },
  { id: '0P7DE12WSXQMM', name: "트래버스", category: "쉐보레" },
  { id: '0P7DE12WSXQJ5', name: "프리미어리그", category: "해외축구 " },
  { id: '0P7DE12WSXQJ6', name: "라리가", category: "해외축구 " },
  { id: '0P7DE12WSXQJ7', name: "세리에 A", category: "해외축구 " },
  { id: '0P7DE12WSXQJ8', name: "분데스리가", category: "해외축구 " },
  { id: '0P7DE12WSXQJ9', name: "리그1", category: "해외축구 " },
  { id: '0P7DE12WSXQJA', name: "챔피언스리그", category: "해외축구 " },
  { id: '0P7DE12WSXQJB', name: "2026 북중미 월드컵", category: "해외축구 " },
  { id: '0P7DE12WSXQJD', name: "해외축구 기타", category: "해외축구 " },
  { id: '0P7DE12WSXQJE', name: "MLS", category: "해외축구 " },
  { id: '0P7DE12WSXQNS', name: "정비/수리 Q&A", category: "자동차 정비/수리" },
  { id: '0P7DE12WSXQNT', name: "정비/수리 후기", category: "자동차 정비/수리" },
  { id: '0P7DE12WSXQJP', name: "골프", category: "골프" },
  { id: '0P7DE12WSXQNQ', name: "블랙박스", category: "자동차 제보" },
  { id: '0P7DE12WSXQNR', name: "스파이샷", category: "자동차 제보" },
  { id: '0P7DE12WNXQJ1', name: "해외야구", category: "해외야구" },
  { id: '0P7DE12WSXQNV', name: "튜닝/커스텀/DIY", category: "자동차 튜닝/DIY" },
  { id: '0P7DE12WSXQM4', name: "GV80", category: "제네시스" },
  { id: '0P7DE12WSXQM3', name: "G80", category: "제네시스" },
  { id: '0P7DE12WSXQM7', name: "GV70", category: "제네시스" },
  { id: '0P7DE12WSXQM5', name: "G70", category: "제네시스" },
  { id: '0P7DE12WSXQM6', name: "G90", category: "제네시스" },
  { id: '0P7DE12WSXQM8', name: "GV60", category: "제네시스" },
  { id: '0P7DE12WSXQK2', name: "투싼", category: "현대자동차" },
  { id: '0P7DE12WSXQK3', name: "아반떼", category: "현대자동차" },
  { id: '0P7DE12WSXQK4', name: "쏘나타", category: "현대자동차" },
  { id: '0P7DE12WSXQK5', name: "싼타페", category: "현대자동차" },
  { id: '0P7DE12WSXQK6', name: "그랜저", category: "현대자동차" },
  { id: '0P7DE12WSXQK7', name: "포터", category: "현대자동차" },
  { id: '0P7DE12WSXQK8', name: "코나", category: "현대자동차" },
  { id: '0P7DE12WSXQK9', name: "넥쏘", category: "현대자동차" },
  { id: '0P7DE12WSXQKA', name: "팰리세이드", category: "현대자동차" },
  { id: '0P7DE12WSXQKB', name: "베뉴", category: "현대자동차" },
  { id: '0P7DE12WSXQKC', name: "아이오닉 5", category: "현대자동차" },
  { id: '0P7DE12WSXQKD', name: "스타리아", category: "현대자동차" },
  { id: '0P7DE12WSXQKE', name: "캐스퍼", category: "현대자동차" },
  { id: '0P7DE12WSXQKF', name: "아이오닉 6", category: "현대자동차" },
  { id: '0P7DE12WSXQKG', name: "ST1", category: "현대자동차" },
  { id: '0P7DE12WSXQKH', name: "아이오닉 9", category: "현대자동차" },
];

const CHANNEL_BASE_URL = 'https://lounge.naver.com/channels/';

function getChannelUrl(id) {
  return CHANNEL_BASE_URL + id;
}

function extractChannelId(url) {
  const m = url.match(/lounge\.naver\.com\/channels\/([A-Z0-9]+)/i);
  return m ? m[1] : null;
}

function getAllLounges(customLounges = []) {
  const combined = [...LOUNGE_DB, ...customLounges];
  const seen = new Set();
  return combined.filter(l => {
    if (seen.has(l.id)) return false;
    seen.add(l.id);
    return true;
  });
}

function groupByCategory(lounges) {
  const groups = {};
  for (const l of lounges) {
    if (!groups[l.category]) groups[l.category] = [];
    groups[l.category].push(l);
  }
  return groups;
}

function findLounge(id, customLounges = []) {
  return getAllLounges(customLounges).find(l => l.id === id) || null;
}
